export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

export const FETCH_NODE_BLOCKS_START = 'FETCH_NODE_BLOCKS_START';
export const FETCH_NODE_BLOCKS_SUCCESS = 'FETCH_NODE_BLOCKS_SUCCESS';
export const FETCH_NODE_BLOCKS_FAILURE = 'FETCH_NODE_BLOCKS_FAILURE';
